version: '3.8'

services:
  mock-psql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "db.data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    tty: true

volumes:
  db.data:
    external: true
